version: '3.9'

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3305:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
