version: '3.9'

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3305:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - laravel_mysql_network
  
volumes:
  db_data:

networks:
  laravel_mysql_network:
    external: true
